### ISSUE TITLE
(un-)export ggproto objects

### ISSUE THREAD

**Issue by corybrunson** [garretrc/ggvoronoi#4]
The `'ggproto'` object `StatVoronoi` is exported but not documented; should it be un-exported (like `GeomVoronoi`)? or should both be exported (and documented)?

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1096)._

**Comment by garretrc** [comment]
StatVoronoi should be exported so it can be called via stat="voronoi" in any ggplot2 geom, but GeomVoronoi is more of a convenience function: people are used to calling geom_* in ggplot rather than stat_*. We debated removing geom_voronoi entirely, as it technically works the same as the default behavior of stat_voronoi, but ultimately decided to include the function as a convenience to users. 

As of now, StatVoronoi does not have its own .Rd file but calling ?StatVoronoi brings up the documentation page for stat_voronoi. ggplot2 handles calls to Stat* by bringing up the documentation page for ggplot2-ggproto, so I think the behavior of ?StatVoronoi is appropriate, unless you think an additional .Rd file is called for in this instance or have a different idea!

**Comment by corybrunson** [comment]
Oh! I see—`geom_voronoi` produces a layer using `GeomPolygon`! I had noticed that earlier but somehow forgot it when raising the issue.

I have a personal qualm with having a layer without an associated ggproto object, but perhaps that's not uncommon and i just haven't noticed it. I also got into the habit of calling `geom_*` by default, though recently i've tried to get into the habit of calling whichever layer function better communicates (to the code reader) the purpose of the resulting graphic.

But there's certainly room for different conventions here, and yours might ultimately be more useful than mine. And i see that it's not an oversight, so it no longer holds up my review. Thanks for the explanation!

**Comment by garretrc** [comment]
Thanks! I'll close the issue. This was a source of weeks of debate for us when we were first creating the package, resulting in a number of conversations with @kmaurer, my data viz prof and a contributor to the package, about whether or not to include geom_voronoi. Ultimately, we decided to keep it in order to have a more familiar syntax (like geom_point and geom_line etc.). 

Early on in development when I was reading Hadley's guide to extending ggplot2 (http://rstudio-pubs-static.s3.amazonaws.com/108934_8537676801dd4548a96f6451bae01e94.html) he said something regarding having geom_* and stat_* instead of layer_* was a "mistake", and since reading that I've been more willing to choose user convenience over what is most likely "correct" (which would be having only stat_voronoi and no geom_*). Overall I think we made a good choice, but I do tend to use stat_voronoi over geom_voronoi personally!
